# Generated by Django 5.1.4 on 2025-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='Acct_Name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
