# Generated by Django 5.1.4 on 2025-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_ticketdetails_acct_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='busdetails',
            name='AgencyName',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
