# Generated by Django 5.1.4 on 2025-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_delete_user_busdetails_agencyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_username', models.CharField(max_length=100, unique=True)),
                ('Driver_Name', models.CharField(max_length=100)),
                ('Driver_DOB', models.DateField()),
                ('DL_DOE', models.DateField()),
                ('Driver_License_No', models.CharField(max_length=100)),
                ('Driver_Address', models.TextField()),
                ('Driver_Contact', models.CharField(max_length=100)),
            ],
        ),
    ]
