# Generated by Django 5.1.4 on 2025-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_driverdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='BusStatus',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='Driver',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='TicketStatus',
            field=models.CharField(default='Booked', max_length=100),
        ),
        migrations.AlterField(
            model_name='driverdetails',
            name='Driver_Address',
            field=models.TextField(default='bro is homeless'),
        ),
    ]
